Repository cs361w2019-osu/sprint1-project-group-17, pull requests merged in 2019-02, with the labels that each got.

#28 Added a message when accessing on a screen that isnt an ipad or ipad pro.
  src/main/java/assets/css/custom.css
  src/main/java/views/ApplicationController/index.ftl.html
Labels: feature

#56 Increase Test Coverage
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
  src/test/java/cs361/battleships/models/ShipTest.java
  src/test/java/cs361/battleships/models/SquareTest.java
Labels: enhancement, sprint 3

#57 added bootstrap js alert informing users of new features.
  src/main/java/views/ApplicationController/index.ftl.html
  src/main/java/views/layout/defaultLayout.ftl.html
Labels: UI, enhancement
